#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx nx affected --target=lint
echo 'nx affected --target=lint passed'

npx nx affected --target=test
echo 'nx affected --target=test'

echo 'all checks passed! here we go! 🚀'
