name: Build and test

on:
  push:
    branches:
      - '!main'
  pull_request:

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v2
      - run: npm ci
      - run: npm install
      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --target=lint
      - run: npx nx affected --target=test --ci --code-coverage
